<?php
/**
 *
 * @author: xaboy<365615158@qq.com>
 * @day: 2017/12/11
 */

namespace app\wap\controller;


use app\wap\model\user\User;
use app\wap\model\user\WechatUser;
use behavior\wap\WapBehavior;
use service\JsonService;
use think\Controller;
use behavior\wechat\UserBehavior;
use service\HookService;
use service\UtilService;
use app\core\util\WechatService;
use think\Cookie;
use think\Request;
use think\Session;
use think\Url;

class WapBasic extends Controller 
{
    protected function _initialize()
    {

        parent::_initialize(); // TODO: Change the autogenerated stub
        $spreadUid = Request::instance()->route('spuid',0);
        if($spreadUid
            && ($userInfo = User::getUserInfo(WechatUser::openidToUid($this->oauth())))
            && !$userInfo['spread_uid']
            && $userInfo['uid'] != $spreadUid
        ) User::edit(['spread_uid'=>$spreadUid,'spread_time'=>time()],$userInfo['uid'],'uid');
        HookService::listen('wap_init',null,null,false,WapBehavior::class);
        $this->assign('Version',['android'=>108,'ios'=>101,'android_url'=>'http://www.pinlehui8.com/xzapp.html','ios_url'=>'url']);
    
    }

    /**
     * 操作失败 弹窗提示
     * @param string $msg
     * @param int $url
     * @param string $title
     */
    protected function failed($msg = '操作失败', $url = 0, $title='')
    {
        if($title==''){
            $title=L('資訊提示','Information tips');
        }
        if($this->request->isAjax()){
            exit(JsonService::fail($msg,$url)->getContent());
        }else {
            $this->assign(compact('title', 'msg', 'url'));
            exit($this->fetch('public/error'));
        }
    }

    /**
     * 操作成功 弹窗提示
     * @param $msg
     * @param int $url
     */
    protected function successful($msg = '操作成功', $url = 0, $title='')
    {
        if($title==''){
            $title=L('成功提示','Success prompt');
        }
        if($this->request->isAjax()){
            exit(JsonService::successful($msg,$url)->getContent());
        }else {
            $this->assign(compact('title', 'msg', 'url'));
            exit($this->fetch('public/success'));
        }
    }

    public function _empty($name)
    {
        $url = strtolower($name) == 'index' ? Url::build('Index/index','',true,true) : 0;
        return $this->failed('请求页面不存在!',$url);
    }
  /*
   判断是否登录
  */
   protected function is_login(){
     try{
            $uid = User::getActiveUid();
        }catch (\Exception $e){
            Cookie::set('is_login',0);
            $url=$this->request->url(true);
            return $this->redirect(Url::build('Login/index').'?ref='.base64_encode(htmlspecialchars($url)));
        }
        $this->userInfo = User::getUserInfo($uid);
        if(!$this->userInfo || !isset($this->userInfo['uid'])) return $this->failed('读取用户信息失败!');
        if(!$this->userInfo['status']) return $this->failed('已被禁止登陆!');
        $this->uid = $this->userInfo['uid'];
        $this->assign('userInfo',$this->userInfo);
   }
    /**
     * 微信用户自动登陆
     * @return string $openid
     */
    protected function oauth()
    {
        $openid = Session::get('loginOpenid','wap');
        if($openid) return $openid;
        if(!UtilService::isWechatBrowser()) exit($this->failed('请在微信客户端打开链接'));
        if($this->request->isAjax()) exit($this->failed('请登陆!'));
        $errorNum = (int)Cookie::get('_oen');
        if($errorNum && $errorNum > 3) exit($this->failed('微信用户信息获取失败!!'));
        try{
            $wechatInfo = WechatService::oauthService()->user()->getOriginal();
        }catch (\Exception $e){
            Cookie::set('_oen',++$errorNum,900);
            exit(WechatService::oauthService()->scopes(['snsapi_base'])
                ->redirect($this->request->url(true))->send());
        }
        if(!isset($wechatInfo['nickname'])){
            $wechatInfo = WechatService::getUserInfo($wechatInfo['openid']);
            if(!$wechatInfo['subscribe'] && !isset($wechatInfo['nickname']))
                exit(WechatService::oauthService()->scopes(['snsapi_userinfo'])
                    ->redirect($this->request->url(true))->send());
            if(isset($wechatInfo['tagid_list']))
                $wechatInfo['tagid_list'] = implode(',',$wechatInfo['tagid_list']);
        }else{
            if(isset($wechatInfo['privilege'])) unset($wechatInfo['privilege']);
            $wechatInfo['subscribe'] = 0;
        }
        Cookie::delete('_oen');
        $openid = $wechatInfo['openid'];
        HookService::afterListen('wechat_oauth',$openid,$wechatInfo,false,UserBehavior::class);
        Session::set('loginOpenid',$openid,'wap');
        Cookie::set('is_login',1);
        return $openid;
    }

}